apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default
  namespace: kubeflow-user
spec:
 rules:
  - to:
    - operation:
        methods: ["GET","POST"]
        paths: #FILL IN
