apiVersion: v1
kind: Service
metadata:
  labels:
    app: pet-bokeh
  name: pet-bokeh-service
  namespace: kubeflow-user
spec:
  ports:
  - name: http-tf-serving
    port: #FILL IN
    targetPort: #FILL IN
    nodePort: 31000
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
    nodePort: 31001
  selector:
    app: pet-bokeh
  type: NodePort
